services:
  postgres:
    image: postgres:15
    container_name: postgres-gamestudio
    restart: unless-stopped
    environment:
      POSTGRES_DB: gamestudio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - /Users/shah/Back-End-Development/Back-End-Development/Course-Assignments/sql-assignment/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-gamestudio
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gamestudio.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - postgres
